version: 0.2

env: 
  variables:
    STAGE: prod
    SERVICE: exampleservice
    PROJECT: MozDef-EF
    TYPE: <event-source-type>
    API_PATH: /example/event/api
    TOKEN_ARN: "arn:aws:ssm:<REGION_NAME>:<ACCOUNT_ID>:parameter/<parameter-name>"
  ssm:

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      # Install dependencies here
  pre_build:
    commands:
      # Perform pre-build actions here, maybe tests for instance
  build:
    commands:
      # Invoke the deploy script here